/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import conexionbd.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ERNESTO GARCIA
 */
public class EliminarPaquete extends javax.swing.JFrame {

    /**
     * Creates new form EliminarPaquete
     */
    public EliminarPaquete() {
        initComponents();
        this.setTitle("Elimnar paquetes");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TF_Busqueda_remitente = new javax.swing.JTextField();
        Boton_Eliminar = new javax.swing.JButton();
        Boton_Limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Busqueda = new javax.swing.JTable();
        Boton_Mostra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TF_Eliminar_remitente1 = new javax.swing.JTextField();
        B_Eliminar = new javax.swing.JButton();
        Boton_Limpiar_Eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Busqueda1 = new javax.swing.JTable();
        Boton_Mostra_Eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 3, 12)); // NOI18N
        jLabel1.setText("Eliminar Remitentes");

        Boton_Eliminar.setText("Eliminar");

        Boton_Limpiar.setText("Limpiar");

        Tabla_Busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Remitente", "Destinatario", "Tipo", "Fragil", "Peso", "Clase", "Forma", "Detalles"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Busqueda);

        Boton_Mostra.setText("Mostra");

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jLabel2.setText("Ingresa el Nombre del Remitente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setForeground(new java.awt.Color(153, 255, 204));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 3, 12)); // NOI18N
        jLabel3.setText("Eliminar Remitentes");

        TF_Eliminar_remitente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Eliminar_remitente1ActionPerformed(evt);
            }
        });

        B_Eliminar.setText("Eliminar");
        B_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EliminarActionPerformed(evt);
            }
        });

        Boton_Limpiar_Eliminar.setText("Limpiar");
        Boton_Limpiar_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Limpiar_EliminarActionPerformed(evt);
            }
        });

        Tabla_Busqueda1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Remitente", "Destinatario", "Tipo", "Fragil", "Peso", "Clase", "Forma", "Detalles"
            }
        ));
        jScrollPane2.setViewportView(Tabla_Busqueda1);

        Boton_Mostra_Eliminar.setText("Mostra");
        Boton_Mostra_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Mostra_EliminarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jLabel4.setText("Ingresa el Nombre del remitentes a buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TF_Eliminar_remitente1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(B_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_Limpiar_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_Mostra_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(209, 209, 209))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Eliminar_remitente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Eliminar)
                    .addComponent(Boton_Limpiar_Eliminar)
                    .addComponent(Boton_Mostra_Eliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_Eliminar_remitente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Eliminar_remitente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Eliminar_remitente1ActionPerformed

    private void B_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EliminarActionPerformed
        // TODO add your handling code here:
        String nombreEliminar= TF_Eliminar_remitente1.getText().trim();
        
        if(!nombreEliminar.isEmpty()){
            int confimacion= JOptionPane.showConfirmDialog(this,"Estas seguro de que deseas eliminar este registro?"
            ,"Confirmacion de Elinacion", JOptionPane.YES_NO_OPTION);
            
            if(confimacion==JOptionPane.YES_OPTION){
                try{
                    eliminarRegistro(nombreEliminar);
                }catch(SQLException ex){
                     Logger.getLogger(EliminarPaquete.class.getName()).log(Level.SEVERE, null, ex);
                }
                  
            }else{
                JOptionPane.showMessageDialog(this, "Operacion de Eliminar Cancelada");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingresa un nombre para buscar y eliminar");
        }

    }//GEN-LAST:event_B_EliminarActionPerformed

    private void Boton_Limpiar_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Limpiar_EliminarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        limpiarCampoBuscar();
    }//GEN-LAST:event_Boton_Limpiar_EliminarActionPerformed

    private void Boton_Mostra_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Mostra_EliminarActionPerformed
        // TODO add your handling code here:
        try{
            cargarDatosTabla();

        }catch(SQLException ex){
            Logger.getLogger(MostraPaquetes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Boton_Mostra_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarPaquete().setVisible(true);
            }
        });
    }
    
    
    //Limpuar tabla
     private void limpiarTabla() {
    DefaultTableModel model = (DefaultTableModel) Tabla_Busqueda1.getModel(); // Usa 'getModel' en lugar de 'getmodel'
    model.setRowCount(0); // Elimina todas las filas de la tabla
}
    
     //Limpiar campo de busqueda 
private void limpiarCampoBuscar() {
    TF_Eliminar_remitente1.setText(""); // Limpia el contenido del campo de búsqueda
}

//Carga de datos
private void cargarDatosTabla() throws SQLException {
         DefaultTableModel model = new DefaultTableModel();
         model.addColumn("remitente");
    model.addColumn("destinatario");
    model.addColumn("tipo");
    model.addColumn("fragil");
    model.addColumn("peso");
    model.addColumn("clase");
    model.addColumn("forma");
    model.addColumn("detalles");
    Tabla_Busqueda1.setModel(model);
    
    ConexionBD conec = new ConexionBD("paqueteria");
    Connection conn = conec.conexion();
    
    if (conn != null) {
        try {
            String query = "SELECT * FROM paqueteria";
            PreparedStatement preparedStatement = conn.prepareStatement(query);
            ResultSet resultSet = preparedStatement.executeQuery();

            while (resultSet.next()) {
                String[] rowData = {
                    resultSet.getString("remitente"),
                    resultSet.getString("destinatario"),
                    resultSet.getString("tipo"),
                    resultSet.getString("fragil"),
                    resultSet.getString("peso"),
                    resultSet.getString("clase"),
                    resultSet.getString("forma"),
                    resultSet.getString("detalles")
                };
                model.addRow(rowData);
            }

            resultSet.close();
            preparedStatement.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            if (conn != null) {
                conn.close();
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo conectar a la base de datos.");
    }
}


//Eliminar Registro
private void eliminarRegistro(String nombre) throws SQLException{
    ConexionBD conec =new ConexionBD("paqueteria");
    Connection conn= conec.conexion();
    
    if(conn != null){
        try{
            String querty= "DELETE FROM paqueteria WHERE remitente=?";
            PreparedStatement preparedStatement= conn.prepareStatement(querty);
            preparedStatement.setString(1, nombre);
            int rowCount=preparedStatement.executeUpdate();
            
            if(rowCount >0){
                JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente");
                cargarDatosTabla();
            }else{
                JOptionPane.showMessageDialog(this, "No se encontro ningun registro a eliminar");
            }
            preparedStatement.close();
            
        }catch(SQLException ex){
            ex.printStackTrace();
        }finally{
            conn.close();
        }
    }else{
        JOptionPane.showMessageDialog(this, "No se puede conectar a la base de datos");
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Eliminar;
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JButton Boton_Limpiar;
    private javax.swing.JButton Boton_Limpiar_Eliminar;
    private javax.swing.JButton Boton_Mostra;
    private javax.swing.JButton Boton_Mostra_Eliminar;
    private javax.swing.JTextField TF_Busqueda_remitente;
    private javax.swing.JTextField TF_Eliminar_remitente1;
    private javax.swing.JTable Tabla_Busqueda;
    private javax.swing.JTable Tabla_Busqueda1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}


